##########################################################
###################  生产环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://192.168.103.38:3030/lingshan_eshop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 9ijtkdeY7RXS0eOG
    filters: log4j,wall,mergeStat
  redis:
    host: 192.168.103.38
    port: 7000
    password: admin
    #平台端database为0
    #    database: 0
    #商家端database为1
    database: 1
  rabbitmq:
    addresses: 192.168.103.38:5672
    username: eshop
    password: 123456
    virtual-host: /eshop
    publisher-confirms: true  # 开启发送消息到exchange确认机制
    publisher-returns: true   # 开启发送消息到exchange但是exchange没有和队列绑定的确认机制
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

#多数据源
guns:
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://172.16.0.251:3306/biz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
  url-prefix:
    messageurl: http://192.168.103.37:8686/smsg #短信发送平台 服务器接口
  #    bathurl: http://xjcyxyx.oauth.echoface.online #项目路径前缀
  spring-session-open: true
  masterDomain: https://account.jxlingshan.cn/accountAdmin
  curSystem: 3
  masterLoginUrl: ${guns.masterDomain}/login/${guns.curSystem}
  domainName: jxlingshan.cn


  #fastdfs文件上传
  fastDfs-url:
    trackers: 192.168.103.38:22122
    visit: https://images.jxlingshan.cn/  #文件访问的URL包括端口信息

#微信支付
pay:
  wxpay:
    appid: wx2fb7461b4ce0c888
    mchid: 1525628691
    key: b8168cc7c2a711e9a35e0242ac110002
    certpath: apiclient_cert_pro.p12

logging:
  level.root: info
  level.cn.ibdsr: debug
  path: logs/
  file: guns.log